# Generated by Django 4.0.2 on 2022-02-13 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('poster_link', models.URLField()),
                ('released_year', models.CharField(max_length=4)),
                ('duration_in_min', models.CharField(max_length=7)),
                ('imdb_rating', models.CharField(max_length=2)),
                ('overview', models.CharField(max_length=1280)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movie_app.director')),
                ('star1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='star1', to='movie_app.actor')),
                ('star2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='star2', to='movie_app.actor')),
                ('star3', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='star3', to='movie_app.actor')),
                ('star4', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='star4', to='movie_app.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=526, null=True)),
                ('date_recommended', models.DateField()),
                ('is_watched_by_receiver', models.BooleanField(blank=True, null=True)),
                ('date_watched_by_receiver', models.DateField(blank=True, null=True)),
                ('receiver_rating', models.CharField(choices=[('1', '1 STARS'), ('2', '2 STARS'), ('3', '3 STARS'), ('4', '4 STARS'), ('5', '5 STARS')], max_length=1)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movie_app.moviedata')),
                ('recommend_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recommend_to', to=settings.AUTH_USER_MODEL)),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recommender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_watch', models.DateField()),
                ('rating', models.CharField(choices=[('1', '1 STARS'), ('2', '2 STARS'), ('3', '3 STARS'), ('4', '4 STARS'), ('5', '5 STARS')], max_length=1)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movie_app.moviedata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movie_app.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movie_app.moviedata')),
            ],
        ),
    ]
