# Generated by Django 4.0.2 on 2022-02-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='director',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='star1',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='star2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='star3',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='star4',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
