# Generated by Django 4.0.2 on 2022-02-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_remove_moviegenres_genre_remove_moviegenres_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='duration_in_min',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='imdb_rating',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='released_year',
            field=models.CharField(max_length=5),
        ),
    ]
