# Generated by Django 4.0.2 on 2022-02-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_moviedata_duration_in_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='receiver_rating',
            field=models.CharField(blank=True, choices=[('1', '1 STARS'), ('2', '2 STARS'), ('3', '3 STARS'), ('4', '4 STARS'), ('5', '5 STARS')], max_length=1, null=True),
        ),
    ]
