# Generated by Django 4.0.2 on 2022-02-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_recommendations_receiver_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalwatchlist',
            name='rating',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
