# Generated by Django 4.0.2 on 2022-02-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_alter_personalwatchlist_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalwatchlist',
            old_name='rating',
            new_name='liked',
        ),
    ]
